// ────────────────────────────────────────────────────────
// Attention system — type definitions
// ────────────────────────────────────────────────────────

/** Categories of attention items. */
export type AttentionType =
  | "issue_stale"
  | "pr_needs_review"
  | "ci_failing"
  | "session_idle";

/** Severity levels for attention items. */
export type AttentionSeverity = "info" | "warning" | "critical";

/** A single attention item generated by the rule engine. */
export interface AttentionItem {
  /** Unique identifier (deterministic from type + project + source). */
  id: string;
  /** What kind of attention is needed. */
  type: AttentionType;
  /** How urgent. */
  severity: AttentionSeverity;
  /** Project reference (owner/repo). */
  project: string;
  /** Human-readable description. */
  message: string;
  /** When this item was first generated. */
  createdAt: string;
  /** Link to the relevant GitHub resource (issue, PR, commit). */
  url?: string;
  /** Source identifier (e.g. issue number, PR number). */
  sourceId?: string;
  /** Whether the user has dismissed this item. */
  dismissed: boolean;
}

/** Configuration for a single attention rule. */
export interface AttentionRuleConfig {
  /** Rule identifier matching the AttentionType. */
  type: AttentionType;
  /** Whether this rule is active. */
  enabled: boolean;
  /** Rule-specific parameters. */
  params: Record<string, unknown>;
}

/** Full attention system configuration. */
export interface AttentionConfig {
  /** How often to evaluate rules (milliseconds). */
  evaluationIntervalMs: number;
  /** Maximum number of items to retain in memory. */
  maxItems: number;
  /** Rule configurations. */
  rules: AttentionRuleConfig[];
}

/** Default configuration with sensible defaults. */
export function defaultAttentionConfig(): AttentionConfig {
  return {
    evaluationIntervalMs: 5 * 60 * 1000, // 5 minutes
    maxItems: 500,
    rules: [
      {
        type: "issue_stale",
        enabled: true,
        params: { staleDays: 14 },
      },
      {
        type: "pr_needs_review",
        enabled: true,
        params: {},
      },
      {
        type: "ci_failing",
        enabled: true,
        params: {},
      },
      {
        type: "session_idle",
        enabled: true,
        params: { idleMinutes: 5 },
      },
    ],
  };
}

/** Query filters for listing attention items. */
export interface AttentionQuery {
  severity?: AttentionSeverity;
  project?: string;
  type?: AttentionType;
  dismissed?: boolean;
}
